"""add new table OrderItem

Revision ID: bc716b3a24a5
Revises: d026094152f8
Create Date: 2025-10-09 16:26:20.000117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc716b3a24a5'
down_revision: Union[str, Sequence[str], None] = 'd026094152f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create the new 'order_items' table
    op.create_table('order_items',
        sa.Column('id', sa.BigInteger(), sa.Identity(start=1), nullable=False),
        sa.Column('order_id', sa.BigInteger(), nullable=False),
        sa.Column('cuisine_id', sa.BigInteger(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('size', sa.String(length=10), nullable=False),
        sa.Column('price_at_purchase', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Step 2: Create foreign keys to link 'order_items' to 'orders' and 'cuisines'
    op.create_foreign_key(
        'fk_order_items_order_id', 'order_items', 'orders',
        ['order_id'], ['id']
    )
    op.create_foreign_key(
        'fk_order_items_cuisine_id', 'order_items', 'cuisines',
        ['cuisine_id'], ['id']
    )

    # Step 3: Drop the old 'items' column from the 'orders' table
    op.drop_column('orders', 'items')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
